### ISSUE TITLE
pdfmerge fails if files have relative paths

### ISSUE THREAD

**Issue by jeremysanders** [dmaphy/pdfmerge#1]
This is with pdfmerge-1.0.3-1.fc14.noarch (Fedora 14 version). If I use input files with relative paths I get:

<pre>
system:~/mydir:$ pdfmerge in1.pdf ../in2.pdf out.pdf
Error: /invalidfileaccess in --run--
Operand stack:
   (./../in2.pdf)   (r)
Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   1878   1   3   %oparray_pop   1877   1   3   %oparray_pop   1861   1   3   %oparray_pop   1755   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   1878   1   4   %oparray_pop   --nostringval--
Dictionary stack:
   --dict:1158/1684(ro)(G)--   --dict:1/20(G)--   --dict:75/200(L)--   --dict:75/200(L)--
Current allocation mode is local
Last OS error: 2
Current file position is 386
GPL Ghostscript 8.71: Unrecoverable error, exit code 1
</pre>

It works fine if I copy the ../in2.pdf to the current directory and use that instead.

**Comment by dschwoerer** [comment]
`pdfmerge ../a.pdf b.pdf all.pdf`
is still not working on `1.0.5-5.fc26` and `1.0.5-7.fc27`

Using the master branch works - but not the version shipped in fedora ...

**Comment by msphn** [comment]
So I assume we can close this one again since we tagged a new major? If not => reopen :-)
