### ISSUE TITLE
Download link

### ISSUE THREAD

**Issue by dschwoerer** [dmaphy/pdfmerge#12]
The current version of pdfmerge is 1.0.6. You can obtain it from here:
https://github.com/dmaphy/pdfmerge/archive/1.0.6.tar.gz

The link is invalid.
The most recent release seems to be from 2014, and is version 1.0.5:
https://github.com/dmaphy/pdfmerge/releases

**Comment by dschwoerer** [comment]
PS: I think you should be able to create the 1.0.6 release [here](https://github.com/dmaphy/pdfmerge/releases/new)

That way fedora and other downstream projects can more easily ship the fixed version.

And thanks for pdfmerge 👍

**Comment by msphn** [comment]
I created a pre-release, that makes the link work. Someone might want to test it in case it's not and then set it to release.

**Comment by msphn** [comment]
Well, looks good to me, I close this one.
Reopen if you see any issues here!

**Comment by dschwoerer** [comment]
Perfect, thanks :+1:
