### ISSUE TITLE
return 255 with no error messages on Linux

### ISSUE THREAD

**Issue by mikhailidim** [dmaphy/pdfmerge#8]
Your program is awesome, but one single scratch.
If I run it under Fedora 21  with no parameters or with help argument it exits with code 255 (-1 in bash).
From common sense it should be 0, because there is no error to call utility just to check version or get help.

thank you for your great job.
Michael

**Comment by dmaphy** [comment]
Hi Michael, thank you very much for reporting this issue. I've fixed this in 5e601a8 and see if I probably do a release in the next days. :-)
